### PR TITLE
Allow to create Grid with configuration files in resource or in memory.

### PR DESCRIPTION
**Pull request by bozaro**
Main change:
```
Grid.getInstance(String configPath, ...) -> Grid.getInstance(Resource configResource, ...)
```

### CODE REVIEW

**Comment by pron** [comment]
Hi.
I'm a little hesitant about this change because it makes Spring part of the public Galaxy API. How about simply adding a method that takes an `InputStream`?

**Comment by bozaro** [comment]
Hello.
I think, InputStream is not enought, because configuration files can include another configuration files.

In the case of InputStream get the contents of the included file relative link fails. Alternatively Resource can be replaced by URL.
URL allows to get input stream (for resource, local files, remote files etc) and make possible to include config parts by relative links.

**Comment by bozaro** [comment]
But URL also still have trouble with in-memory generated configuration.

**Comment by pron** [comment]
But isn't a Spring `Resource` just a `File`, `URL`, or an `InputStream`?

**Comment by bozaro** [comment]
I think ```URL``` is much better then ```File``` or ```InputStream```.

If you want, I can change Resource to URL in my pull request.

**Comment by pron** [comment]
Yeah, that would be better. And there's no need to depracate the old methods :)

**Comment by bozaro** [comment]
Updated: Resource -> URL.

**Comment by pron** [comment]
Great. Thanks!

**Comment by bozaro** [comment]
Thanks

**Pull request merged**
